### ISSUE TITLE
-b flag not working

### ISSUE THREAD

**Issue by jczech** [RuleWorld/atomizer#5]
It doesn't seem like the -b flag is working properly. I entered this command:

    python sbmlTranslator.py -i BIOMD0000000019.xml -a -b ~/trd3/bionetgen/bng2/BNG2.pl -o BIOMD0000000019.bngl

And received this error:

    pexpect.exceptions.ExceptionPexpect: The command was not found or was not executable: /home/jczech/workspace/RuleWorld/bionetgen/bng2/BNG2.pl.

If you check ./SBMLparser/utils/consoleCommands.py, you can see there's this line:

    bngExecutable = join(home,'workspace','RuleWorld','bionetgen','bng2','BNG2.pl')

So afaict it's not actually parsing the path that's passed with the -b flag, although I haven't looked into it too closely yet.

**Comment by jjtapia** [comment]
I'll look into it. There's some special handling that is done with pexepct depending on the OS given that the library changes names, so maybe at some point it got broken. Which OS did you try it in?

**Comment by jczech** [comment]
It wasn't working for me in Linux or OSX. I didn't try the -b flag in Windows. I pushed a fix for it, so hopefully it's good now. I'll close this and create a new issue if I find any os specific problems. Thanks!
